export type Industry =
  | 'Construction'
  | 'SaaS'
  | 'Coaching'
  | 'Developer'
  | 'Marketing'
  | 'Finance'
  | 'Healthcare'
  | 'Real Estate'
  | 'HR'
  | 'Other';

export type ContentGoal =
  | 'Authority Building'
  | 'Lead Generation'
  | 'Personal Brand'
  | 'Thought Leadership';

export const INDUSTRY_CONTEXTS: Record<string, Record<string, string[]>> = {
  Construction: {
    'Authority Building': [
      'project delays and how to handle them',
      'contractor coordination challenges',
      'safety compliance lessons',
      'budget overruns and recovery',
      'on-site leadership lessons',
      'leadership under pressure',
      'subcontractor management',
    ],
    'Lead Generation': [
      'client testimonials and project wins',
      'before-and-after transformations',
      'common client mistakes to avoid',
      'how to choose the right contractor',
      'hidden costs in construction projects',
      'questions to ask before hiring',
    ],
    'Personal Brand': [
      'my journey in construction',
      'lessons from the job site',
      'why I chose this trade',
      'personal stories from builds',
      'mistakes that shaped me',
      'values that drive my work',
    ],
    'Thought Leadership': [
      'the future of green construction',
      'modular building trends',
      'tech disrupting the industry',
      'workforce development challenges',
      'sustainability in construction',
      'innovation in building materials',
    ],
  },
  SaaS: {
    'Lead Generation': [
      'churn reduction strategies',
      'onboarding friction points',
      'pricing psychology tricks',
      'turning feature requests into wins',
      'customer success stories',
      'product-market fit journey',
      'reducing time-to-value',
    ],
    'Authority Building': [
      'how we grew from 0 to 1000 users',
      'the metrics that actually matter',
      'our biggest product mistakes',
      'what enterprise clients really want',
      'retention over acquisition',
      'building in public lessons',
    ],
    'Thought Leadership': [
      'the future of B2B SaaS',
      'AI-first product strategy',
      'vertical vs horizontal SaaS',
      'the death of freemium',
      'open-source as a growth strategy',
      'product-led vs sales-led growth debate',
    ],
    'Personal Brand': [
      'why I founded my SaaS',
      'bootstrapping vs VC-backed reality',
      'the loneliness of founder life',
      'my product discovery process',
      'failures that taught me everything',
      'the pivot that saved us',
    ],
  },
  Coaching: {
    'Personal Brand': [
      'client transformations I have witnessed',
      'mindset shifts that change everything',
      'mistakes I made as a new coach',
      'finding your coaching niche',
      'discovery call tips that convert',
      'impostor syndrome as a coach',
      'why I became a coach',
    ],
    'Lead Generation': [
      'signs you need a coach right now',
      'ROI of investing in coaching',
      'what separates good coaches from great',
      'questions to ask before hiring a coach',
      'free vs paid coaching value',
      'my client results in numbers',
    ],
    'Authority Building': [
      'my coaching framework explained',
      'controversial coaching opinions',
      'what no one tells you about transformation',
      'the science behind behavior change',
      'why most coaching fails',
      'accountability structures that work',
    ],
    'Thought Leadership': [
      'the future of human potential development',
      'AI in coaching and development',
      'why traditional management is broken',
      'evidence-based coaching vs intuition',
      'group vs 1-on-1 coaching outcomes',
      'coaching in the corporate world',
    ],
  },
  Developer: {
    'Thought Leadership': [
      'scaling distributed systems',
      'debugging stories with lessons',
      'startup technical mistakes',
      'tech stack tradeoffs no one talks about',
      'system design for growth',
      'AI and the future of programming',
      'when to use microservices vs monolith',
    ],
    'Personal Brand': [
      'my journey from junior to senior',
      'how I landed my first dev job',
      'what I wish I knew starting out',
      'side projects that changed my career',
      'the developer skills nobody talks about',
      'burnout and recovery as a developer',
    ],
    'Authority Building': [
      'code review best practices',
      'architecture decisions I stand by',
      'performance optimization wins',
      'building for maintainability',
      'open source contributions and why',
      'my approach to technical debt',
    ],
    'Lead Generation': [
      'common dev mistakes costing businesses money',
      'signs your codebase needs a consultant',
      'how I audit legacy systems',
      'the real cost of technical debt',
      'what I deliver vs in-house teams',
      'client wins through better engineering',
    ],
  },
  Marketing: {
    'Lead Generation': [
      'campaign that generated 10x ROI',
      'the funnel nobody is talking about',
      'conversion rate optimization secrets',
      'B2B vs B2C content strategies',
      'email marketing that actually converts',
      'paid ads mistakes I have fixed for clients',
    ],
    'Thought Leadership': [
      'the death of third-party cookies',
      'zero-party data and the future',
      'brand vs performance marketing debate',
      'AI in content marketing',
      'community-led growth strategy',
      'short-form video domination',
    ],
    'Authority Building': [
      'my go-to marketing frameworks',
      'how I analyze competitor strategy',
      'metrics that show real growth',
      'why most brands get messaging wrong',
      'brand positioning deep dives',
      'content strategy from scratch',
    ],
    'Personal Brand': [
      'how I got into marketing',
      'campaigns I am most proud of',
      'my creative process revealed',
      'lessons from failed campaigns',
      'how I think about audience first',
      'my philosophy on authentic marketing',
    ],
  },
  Finance: {
    'Authority Building': [
      'investment frameworks that actually work',
      'the financial mistakes most professionals make',
      'how to read a balance sheet fast',
      'tax optimization strategies',
      'cash flow management lessons',
      'financial independence principles',
    ],
    'Lead Generation': [
      'signs you need a financial advisor now',
      'common wealth-destroying mistakes',
      'what good financial planning looks like',
      'estate planning most people ignore',
      'business finance vs personal finance traps',
      'how I helped clients reach financial goals',
    ],
    'Thought Leadership': [
      'the future of DeFi and traditional finance',
      'inflation strategy for 2024 and beyond',
      'ESG investing reality check',
      'private equity accessibility changing',
      'fintech disruption of banking',
      'CBDC implications for wealth',
    ],
    'Personal Brand': [
      'my journey into finance',
      'why I chose this specialization',
      'money lessons from my own mistakes',
      'the mindset shift that changed my finances',
      'why most people fear money conversations',
      'values-based financial planning',
    ],
  },
  Healthcare: {
    'Authority Building': [
      'clinical lessons learned the hard way',
      'patient care innovations I have implemented',
      'how I approach difficult diagnoses',
      'preventive care that gets ignored',
      'interdisciplinary collaboration wins',
      'evidence-based practice in action',
    ],
    'Lead Generation': [
      'signs patients should seek specialist care',
      'questions to ask your doctor',
      'how to navigate the healthcare system',
      'second opinions and why they matter',
      'telehealth advantages and limitations',
      'patient success stories',
    ],
    'Thought Leadership': [
      'AI diagnostics and the future of medicine',
      'mental health crisis and systemic response',
      'preventive care vs reactive medicine',
      'healthcare equity challenges',
      'the doctor shortage problem',
      'wearables and remote patient monitoring',
    ],
    'Personal Brand': [
      'why I chose this medical specialty',
      'the patient story that changed my practice',
      'burnout in healthcare and my experience',
      'what medical school never teaches you',
      'balancing empathy and clinical objectivity',
      'my approach to patient communication',
    ],
  },
  'Real Estate': {
    'Lead Generation': [
      'market timing myths vs reality',
      'common buyer mistakes I see every day',
      'what sellers wish they knew earlier',
      'negotiation tactics that work in this market',
      'hidden costs of buying vs renting',
      'my process for finding off-market deals',
    ],
    'Authority Building': [
      'local market analysis insights',
      'investment property evaluation framework',
      'deal structuring lessons',
      'property management hard truths',
      'real estate cycles and positioning',
      'due diligence checklist walkthrough',
    ],
    'Thought Leadership': [
      'the future of commercial real estate',
      'remote work and suburban migration continues',
      'proptech disrupting the industry',
      'institutional investors impact on housing',
      'short-term vs long-term rental economics',
      'climate risk in real estate valuations',
    ],
    'Personal Brand': [
      'why I chose real estate as a career',
      'my first deal and what it taught me',
      'the deal that almost broke me',
      'building wealth through property my way',
      'client relationships that define my work',
      'my values as an agent',
    ],
  },
  HR: {
    'Authority Building': [
      'hiring mistakes organizations keep making',
      'performance management that actually works',
      'building psychological safety',
      'effective onboarding frameworks',
      'diversity beyond the checkbox',
      'retention strategies that move the needle',
    ],
    'Lead Generation': [
      'signs your company culture is broken',
      'what top talent really wants in 2024',
      'why good employees quit',
      'compensation strategy in a competitive market',
      'how to fix a toxic work environment',
      'the ROI of investing in people',
    ],
    'Thought Leadership': [
      'the future of work post-remote era',
      'AI in hiring: opportunity and risk',
      'four-day work week debate',
      'skills-based hiring over credentials',
      'the end of traditional performance reviews',
      'next generation of employee benefits',
    ],
    'Personal Brand': [
      'why I chose HR as a career',
      'the hardest conversation I ever facilitated',
      'how I think about organizational culture',
      'HR lessons from unexpected places',
      'my philosophy on people-first leadership',
      'my journey from employee to HR leader',
    ],
  },
  Other: {
    'Authority Building': [
      'hard-won lessons in my field',
      'contrarian views that turned out right',
      'frameworks I use daily',
      'mistakes that shaped my expertise',
      'what separates good from great professionals',
      'my decision-making process',
    ],
    'Lead Generation': [
      'signs you need my service right now',
      'common problems I solve',
      'client wins and transformations',
      'what to look for when hiring a professional',
      'questions to ask before working together',
      'my approach to client outcomes',
    ],
    'Personal Brand': [
      'my story and why it matters',
      'values that drive my work',
      'lessons from failures along the way',
      'how I got to where I am today',
      'what I believe about my industry',
      'the moment everything changed for me',
    ],
    'Thought Leadership': [
      'the future of my industry',
      'underrated trends professionals ignore',
      'systemic problems in my field',
      'what innovation looks like in practice',
      'cross-industry lessons that apply',
      'predictions most people disagree with',
    ],
  },
};
